language: ruby
rvm:
  - 2.6
script: ./scripts/cibuild
before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install --jobs=3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
