title: Joseph Ryan
email: josephryan3.14@gmail.com
github_username: p1n3appl3
baseurl: ""
url: https://josephryan.me
permalink: /:title/
markdown: kramdown
highlighter: rouge
description: A personal website to host my portfolio and blog

collections:
  projects:
    output: true
    permalink: /:title/

exclude:
    - README.md
    - vendor
    - scripts
    - Gemfile
    - Gemfile.lock

plugins:
    - jekyll-feed
    - jekyll-mentions
    - jekyll-sitemap

picture:
  source: "assets"

# Tracker
analytics: UA-105628196-1

# Comments
disqus-shortname: p1neapple

# Optimization
sass:
  style: compressed

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
