#!/bin/bash

# enable error reporting to the console
set -e

# cleanup "_site"
rm -rf _site
mkdir _site

# clone remote repo to "_site"
git clone https://${GH_TOKEN}@github.com/p1n3appl3/p1n3appl3.github.io.git _site

# build with Jekyll into "_site"
bundle exec jekyll build

# push
cd _site
git config user.email "josephryan3.14@gmail.com"
git config user.name "Joseph Ryan"
git add --all
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
git push --force origin master

